apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - image: gcr.io/solstice-api-junkyard/app1
          name: hello
          ports:
            - containerPort: 8080
      serviceAccountName: app1